### ISSUE TITLE
where could I download the trained model?

### ISSUE THREAD

**Issue by ardeal** [SangHyeonAn/MnistSimpleCNN#2]
Hi,

where could I download the trained model?

**Comment by arcAman07** [comment]
I had the same question, @ansh941 can I get the file with the downloaded weights and model configurations.

**Comment by ansh941** [comment]
I'm sorry. I looked up the model file after checking this issue, but I couldn't find it.
However, I fixed the random seeds at training, so you will get the same performance by running the train code.
Thank you.
(When I learn that model, I set seed=0 and trials=30.)
